### ISSUE TITLE
TerraForged兼容性问题

### ISSUE THREAD

**Issue by Dr-WeiAL** [MCTeamPotato/Lost-Cities-Potato-Edition#1]
![468~8KDLO(NEQ P8}AS37HE](https://user-images.githubusercontent.com/47446553/230717139-b6104227-0798-4912-b000-57ff2283492a.jpg)
![`5GZ @$UFDVG9AY PX Y(16](https://user-images.githubusercontent.com/47446553/230717144-5f3d9288-5008-4e4e-a014-7b35a277ea4f.png)
和TerraForged一起使用的话会出现这种情况，这个能修吗(

**Comment by Kasualix** [comment]
原lostcities的1.16+全版本也有这个问题，mcjty的回应是：https://github.com/McJtyMods/LostCities/issues/516#issuecomment-1382196894。

**Comment by Dr-WeiAL** [comment]
这个跟他们情况有点不太一样，我这边看的话城市和地形过渡没什么问题，就只是植物浮空了
![image](https://user-images.githubusercontent.com/47446553/230717675-f3cc8292-2b4b-4fe5-94ba-0492a2fb5adc.png)

**Comment by Kasualix** [comment]
我跟OTG+Vanilla Vistas一起用也有这个问题

**Comment by Kasualix** [comment]
先挂着吧，我晚上试试看

**Comment by Dr-WeiAL** [comment]
又遇到不一样的了，补充一下(
![image](https://user-images.githubusercontent.com/47446553/230719912-e2bb8858-8531-475b-b2f6-5995822da57f.png)
![image](https://user-images.githubusercontent.com/47446553/230719933-17815c66-3982-4544-917e-ae356d79bf66.png)

**Comment by Kasualix** [comment]
解决好像是可以解决，但是感觉会造成y256以上城市的cutoff

**Comment by Kasualix** [comment]
村庄问题我刚修好了

**Comment by Dr-WeiAL** [comment]
> > ![image](https://user-images.githubusercontent.com/47446553/230719933-17815c66-3982-4544-917e-ae356d79bf66.png)
> 
> 这个解决好像是可以解决，但是感觉会造成y256以上城市的cutoff ~1165的世界高度在mojang的代码里还各种限制的死死的，根本没法改，我之前想做个提高世界高度上限的mod还泡汤了（~

不太懂，但总比现在这个情况好吧(

**Comment by Dr-WeiAL** [comment]
> 村庄问题我刚修好了

这个似乎是任意结构都会这样，刚刚碰到一个idas生成的建筑也是浮空的，是一起修复了吗？

**Comment by Kasualix** [comment]
这就比较难判了，我建议你抛弃lostcities（

**Comment by Kasualix** [comment]
我去问问mcjty有没有什么好办法

**Comment by Dr-WeiAL** [comment]
好吧，有消息踢我一脚(

**Comment by Kasualix** [comment]
> 好吧，有消息踢我一脚(

[寄了](https://github.com/McJtyMods/LostCities/issues/545#issuecomment-1500893915)

**Comment by Dr-WeiAL** [comment]
> > 好吧，有消息踢我一脚(
> 
> [寄了](https://github.com/McJtyMods/LostCities/issues/545#issuecomment-1500893915)

寄了(悲

**Comment by Kasualix** [comment]
能不能提供一下那些植物出现的最大y坐标？

**Comment by Dr-WeiAL** [comment]
> 能不能提供一下那些植物出现的最大y坐标？

目前能找到的
最高的植物在151格

idas生成的最高的浮空结构在165格
![image](https://user-images.githubusercontent.com/47446553/230726453-dbceb15f-ce38-4956-b5ee-7edc21ee63d6.png)

墓园还会生成浮空墓(
![image](https://user-images.githubusercontent.com/47446553/230726453-dbceb15f-ce38-4956-b5ee-7edc21ee63d6.png)

**Comment by Kasualix** [comment]
妈的，我直接穷举算了，你有哪些结构mod都报上来吧

**Comment by Dr-WeiAL** [comment]
> 妈的，我直接穷举算了，你有哪些结构mod都报上来吧

没了，这个整合包能在地面生成结构的就这两个(

**Comment by Kasualix** [comment]
Graveyard 和 Idas？

**Comment by Dr-WeiAL** [comment]
> Graveyard 和 Idas？

对

**Comment by Kasualix** [comment]
放弃了，bug越搞越多，你还是丢掉 lostcities 算了（

**Comment by Dr-WeiAL** [comment]
![D%ZBO4 )UIE5HZWNF}12R$7](https://user-images.githubusercontent.com/47446553/230732031-bf18c62f-7a2d-48bd-8209-a64c08d167c7.jpg)
